# Uncomment the next line to define a global platform for your project

platform :ios, '14.0'

target 'PackPodAsXCFrameworkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PackPodAsXCFrameworkDemo

  pod 'SnapKit', :podspec => './SnapKit/SnapKit.podspec'
  pod 'FicowPod', :path => './FicowPod'

end


target 'PackPodAsXCFrameworkDemoTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'PackPodAsXCFrameworkDemoUITests' do
  # Pods for testing
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # update IPHONEOS_DEPLOYMENT_TARGET for generated pod projects
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
