# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

all_targets = ["UpdateXcodeprojDemo", "CN-APP", "UK-APP", "US-APP"]
$ficow_targets = []

ficow_config_file = "ficow_enabled_targets.txt" # 配置文件的名称
File.readlines(ficow_config_file).each do |name| # 按行读取文本
  stripped_name = name.strip # strip是一个 Ruby 内置函数，用于移除字符串前后多余的空格
  if !stripped_name.empty? # 如果文本不是空字符串
    $ficow_targets.push(stripped_name) # 加到 FICOW 数组
    puts "Found target #{stripped_name} in ficow_targets" # 打印日志，方便调试
  end
end

all_targets.each do |name| # 遍历所有的 target 名称
  target name do
    if $ficow_targets.include?(name) # 文件中配置的 target 包含当前的 target 名称
      pod 'FICOW', :path => './FICOW' # 引入 FICOW pod
    end
  end
end


def enableFICOWForTargets()
  require 'xcodeproj' # 引入 xcodeproj 库
  project_path = 'UpdateXcodeprojDemo.xcodeproj' # 项目文件名
  project = Xcodeproj::Project.open(project_path)
  condition = "FICOW_ON"
  swift_condition_key = "SWIFT_ACTIVE_COMPILATION_CONDITIONS"
  objc_conditon_key = "GCC_PREPROCESSOR_DEFINITIONS"
  project.targets.each do |target|
    # puts "Started processing FICOW for target: #{target.name}"
    # 添加 FICOW_ON
    if $ficow_targets.include?(target.name)
      target.build_configurations.each do |conf|
        # swift
        swift_condition_string = conf.build_settings[swift_condition_key] # 得到一个字符串值
        puts "swift_condition_string: #{swift_condition_string}, target: #{target.name}, config: #{conf.name}"
        if swift_condition_string.nil? # 旧配置为空
          conf.build_settings[swift_condition_key] = condition
          puts "[Added #{condition} for Swift - nil] swift_conditions: #{conf.build_settings[swift_condition_key]}, target: #{target.name}, config: #{conf.name}"
        else
          unless swift_condition_string.include?(condition)
            conditions = []
            swift_condition_string.split(' ', -1).each do |c|
              stripped_condition = c.strip # 处理多余的空格
              conditions.push(stripped_condition)
            end
            new_condition_string = conditions.push(condition).join(" ")
            conf.build_settings[swift_condition_key] = new_condition_string
            puts "[Added #{condition} for Swift - String] swift_conditions: #{conf.build_settings[swift_condition_key]}, target: #{target.name}, config: #{conf.name}"
          end
        end
        # objc
        objc_conditions = conf.build_settings[objc_conditon_key] # 可能的返回值：nil, 字符串(空字符串、单个元素)，数组（多个元素）
#        puts "objc_conditions: #{objc_conditions}, class:#{objc_conditions.class}"
        if objc_conditions.nil? # 旧配置为空
          conf.build_settings[objc_conditon_key] = condition
          puts "[Added #{condition} for ObjC - nil] objc_conditons: #{conf.build_settings[objc_conditon_key]}, target: #{target.name}, config: #{conf.name}"
          # https://stackoverflow.com/a/15769829
        elsif objc_conditions.is_a?(String) # 通常为 $(inherited)
          conf.build_settings[objc_conditon_key] = [objc_conditions, condition]
          puts "[Added #{condition} for ObjC - String] objc_conditons: #{conf.build_settings[objc_conditon_key]}, target: #{target.name}, config: #{conf.name}"
        elsif objc_conditions.is_a?(Array)
          unless objc_conditions.include?(condition)
            conf.build_settings[objc_conditon_key].push(condition)
            puts "[Added #{condition} for ObjC - Array] objc_conditons: #{conf.build_settings[objc_conditon_key]}, target: #{target.name}, config: #{conf.name}"
          end
        end
      end
      # 去除 FICOW_ON
    else
      # swift
      target.build_configurations.each do |conf|
        swift_condition_string = conf.build_settings[swift_condition_key] # 得到一个字符串值
        if !swift_condition_string.nil? && swift_condition_string.include?(condition)
          conditions = []
          swift_condition_string.split(' ', -1).each do |c|
            stripped_condition = c.strip # 处理多余的空格
            if stripped_condition != condition
#              puts "adding #{stripped_condition} to conditions"
              conditions.push(stripped_condition)
            end
          end
          new_condition_string = conditions.join(" ")
          puts "[Removed #{condition} for Swift] swift_conditions: #{new_condition_string}, target: #{target.name}, config: #{conf.name}"
          conf.build_settings[swift_condition_key] = new_condition_string
        end
        # objc
        objc_conditions = conf.build_settings[objc_conditon_key] # 可能的返回值：nil, 字符串(空字符串、单个元素)，数组（多个元素）
#        puts "objc_conditions: #{objc_conditions}, class:#{objc_conditions.class}"
        unless objc_conditions.nil?
          if objc_conditions.is_a?(String) && objc_conditions.strip == condition
            conf.build_settings[objc_conditon_key] = ""
            puts "[Removed #{condition} for ObjC - String] objc_conditons: #{conf.build_settings[objc_conditon_key]}, target: #{target.name}, config: #{conf.name}"
          elsif objc_conditions.is_a?(Array) && objc_conditions.include?(condition)
            if objc_conditions.length == 1
              conf.build_settings[objc_conditon_key] = ""
            elsif objc_conditions.length == 2
              objc_conditions.delete(condition)
              # puts "objc_conditions.first(): #{objc_conditions.first}"
              conf.build_settings[objc_conditon_key] = objc_conditions.first
            else
              conf.build_settings[objc_conditon_key].delete(condition)
            end
            puts "[Removed #{condition} for ObjC - Array] objc_conditons: #{conf.build_settings[objc_conditon_key]}, target: #{target.name}, config: #{conf.name}"
          end
        end
      end
    end
  end

  project.save() # 保存改动到 .xcodeproj 文件
  puts "Finished processing FICOW for targets"
end


post_install do |installer|
  enableFICOWForTargets()
end


#target 'UpdateXcodeprojDemo' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for UpdateXcodeprojDemo
#
#  target 'UpdateXcodeprojDemoTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'UpdateXcodeprojDemoUITests' do
#    # Pods for testing
#  end
#
#end
